max_rng: 8.0                     # lidar max range
tau: 0.5                         # high pass filter coefficient

t_dist: 0.8                      # target distance [m]

p_dist: 0.6                      # p gain for distance control
p_dir: 0.9                       # p gain for direction control

max_lin_vel: 0.07                # max linear velocity [m/s]
max_ang_vel: 0.8                 # max angular velocity [rad/s]
